export const LAST_7_DAYS_WORKOUT_QUERY = 'LAST_7_DAYS_WORKOUT_QUERY';
export const TODAY_WORKOUT_QUERY = 'TODAY_WORKOUT_QUERY';
export const SUMMARY_LAST_7_DAYS = 'SUMMARY_LAST_7_DAYS';
export const SUMMARY_LAST_30_DAYS = 'SUMMARY_LAST_30_DAYS';
export const CATEGORIES_QUERY = 'CATEGORIES_QUERY';