version: "3.7"
services:
  dbWorkout:
    container_name: postgres
    image: postgres:latest
    ports:
    - "5432:5432"
    volumes:
    - ./data:/var/lib/postgresql/workout
    env_file:
      - .env.local